language: node_js
node_js:
  - "stable"

env:
  - MONGO_URI=mongodb+srv://casder:casder1503@cluster0.q9d6k.mongodb.net/?retryWrites=true&w=majority

before_script:
  - npm install
  - npm run test:dev